{
 "title": "SQL Server - Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dbtype", "label": "Database Type", "query": { "query": "label_values(dbtype)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  { "title": "SQL Server - Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$database - Locks in Database",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sql_server_lock_wait_in_progress{database=\"$database\",dbtype=\"sqlserver\"}",
     "legendFormat": "Lock Waits in Progress"
    },
    {
     "expr": "sql_server_lock_wait_started_per_sec{database=\"$database\",dbtype=\"sqlserver\"}",
     "legendFormat": "Started Lock Waits per Second"
    }
   ]
  },
  {
   "title": "$database - Lock Average Wait Time (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sql_server_lock_wait_time_avg{database=\"$database\",dbtype=\"sqlserver\"})*1000",
     "legendFormat": "lock_wait_time_avg"
    }
   ]
  },
  {
   "title": "$database - Break Connections  caused by Erros",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_server_kill_connection_errors{database=\"$database\",dbtype=\"sqlserver\"}"
    }
   ]
  },
  {
   "title": "$database - Dead Locks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_server_deadlocks{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"} ",
     "legendFormat": "Dead Locks"
    }
   ]
  },
  {
   "title": "$database - User Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sql_server_user_errors{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}[5m])"
    }
   ]
  },
  { "title": "SQL Server - Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$database - Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_server_connections{database=\"$database\",dbtype=\"$dbtype\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Commited Memory Usage - Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sql_server_mem_usage_percent{database=\"$database\",dbtype=\"sqlserver\"}"
    }
   ]
  },
  {
   "title": "$database - CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sql_server_cpu_usage_percent{database=\"$database\",dbtype=\"sqlserver\"}"
    }
   ]
  },
  {
   "title": "Memory Usage - Resident vs Virtual - GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(((sql_server_resident_memory_bytes{database=\"$database\",dbtype=\"sqlserver\"})/1024)/1024)/1024",
     "legendFormat": "memória residente - GB"
    },
    {
     "expr": "(((sql_server_virtual_memory_bytes{database=\"$database\",dbtype=\"sqlserver\"})/1024)/1024)/1024",
     "legendFormat": "memória virtual - GB"
    }
   ]
  },
  {
   "title": "$database - OS Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sql_server_os_memory_used{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "sql_server_os_memory_available{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "sql_server_os_memory_used{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}+sql_server_os_memory_available{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "SQL Server - Caches, Batches & Pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "$database - Cache Hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sql_server_buffer_cache_hit_ratio{database=\"$database\",dbtype=\"sqlserver\"}",
     "legendFormat": "cache hit"
    }
   ]
  },
  {
   "title": "$database - Batch Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sql_server_batch_requests{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}[5m])",
     "legendFormat": "batch request"
    }
   ]
  },
  {
   "title": "$database - OS Page Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sql_server_os_page_file_used{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Page File - Used"
    },
    {
     "expr": "sql_server_os_page_file_available{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Page File - Available"
    },
    {
     "expr": "sql_server_os_page_file_used{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}+sql_server_os_page_file_available{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Page File - Total"
    }
   ]
  },
  {
   "title": "$database - Page Fault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sql_server_page_fault_count{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}[5m])",
     "legendFormat": "Fault"
    }
   ]
  },
  {
   "title": "$database - Page Like Expectancy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sql_server_page_life_expectancy_seconds{database=\"$database\",dbtype=\"sqlserver\",environment=\"production\"}",
     "legendFormat": "Like Expectancy"
    }
   ]
  },
  {
   "title": "$database - Checkpoint pages/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(sql_server_checkpoint_pages_sec{database=\"fcl-totvs-01\",dbtype=\"sqlserver\",environment=\"production\"}[1h])",
     "legendFormat": "pages/s"
    }
   ]
  }
 ]
}